"""AEGIS utils package."""

from app.utils.logger import get_logger
from app.utils.math_utils import (
    compute_dag_constraint,
    entropy,
    hutchinson_trace,
    is_dag,
    kl_divergence,
    matrix_hadamard,
    sigmoid,
    softplus,
    threshold_adjacency,
    trace_expm,
    wasserstein_1d,
)
from app.utils.metrics_utils import (
    compute_calibration_error,
    compute_confusion_matrix,
    compute_demographic_parity_difference,
    compute_equalized_odds_difference,
    compute_f1,
    compute_precision_recall,
    compute_auc,
    format_metric_value,
)
from app.utils.validation import (
    validate_array_shape,
    validate_categorical_values,
    validate_column_exists,
    validate_dataframe,
    validate_model_input,
    validate_not_empty,
    validate_numeric_range,
    validate_probability,
)

__all__ = [
    "get_logger",
    "sigmoid",
    "kl_divergence",
    "entropy",
    "wasserstein_1d",
    "trace_expm",
    "hutchinson_trace",
    "matrix_hadamard",
    "softplus",
    "is_dag",
    "compute_dag_constraint",
    "threshold_adjacency",
    "compute_confusion_matrix",
    "compute_auc",
    "compute_f1",
    "compute_precision_recall",
    "compute_demographic_parity_difference",
    "compute_equalized_odds_difference",
    "compute_calibration_error",
    "format_metric_value",
    "validate_dataframe",
    "validate_model_input",
    "validate_numeric_range",
    "validate_categorical_values",
    "validate_array_shape",
    "validate_probability",
    "validate_column_exists",
    "validate_not_empty",
]
